# Site settings
title: "Evan Hazzard Resume"
description: "Evan W. Hazzard Junior Computer Science Major"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Evan W. Hazzard"
resume_title:                   "Student and Machine Learning Researcher"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ewhazzard@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "217-751-2683"
resume_contact_address:         "512 Landen Lane Fisher, IL 61843"

resume_header_contact_info:     "512 Landen Lane Fisher, IL • 217-751-2683 • ewhazzard@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "Hi! My name is Evan Hazzard and I am a Computer Science major at Illinois State University graduating in the spring of 2023. I like machine learning and data science. "

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ewhazzard"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/evan-hazzard/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://evanhazzard.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
